version: '3'
services:
  angular_cli:
    image: trion/ng-cli:latest
    container_name: 'angular_cli_pp'
    volumes:
      - .:/usr/app/
    working_dir: /usr/app/
    ports:
      - 4200:4200
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0"